---
# tasks file for Apache Zookeeper


- name: "Install OpenJDK Runtime Environment {{ java_version }}"
  yum:
    name: java-{{ java_version }}-openjdk
    state: present
  tags:
    - zookeeper
    - zookeeper:install
    - zookeeper:java

- name: Install zktop
  pip:
    name: zktop
  tags:
    - zookeeper
    - zookeeper:install
    - zookeeper:utills


- name: Install some utilities
  yum:
    name:
      - wget
      - tar
      - net-tools
      - netcat
      #- ca-certificates
    state: latest
  tags:
    - zookeeper
    - zookeeper:install
    - zookeeper:utills


- name: Include configuration tasks
  include: "config.yml"
  tags:
    - zookeeper
    - zookeeper:config


- name: Include Apache Zookeeper tasks
  include: "zookeeper.yml"
  tags:
    - zookeeper
    - zookeeper:install


#
#- name: Zookeeper init.d script
#  template: src=zookeeper-server.j2 dest=/etc/rc.d/init.d/zookeeper-server
#            owner=root group=root backup=yes
#  notify: restart zookeeper
#  tags: zookeeper_install_initd_script
#
#- name: Run daemon-reload
#  systemd:
#    daemon-reload: true
#  tags: zookeeper_install_initd_script
#
#- name: start zookeeper service
#  service: name=zookeeper-server state=started enabled=yes
#  tags: zookeeper_install
#



