---

- hosts: all
  become: yes
  roles:
    - { role: commons, task: timezone,        tags: timezone              }
    ##- { role: commons, task: repos,           tags: repos                 }
    - { role: commons, task: basic_utils,     tags: basic_utils           }
    #- { role: commons, task: users,           tags: groups_users_sshKeys  }
    #- { role: commons, task: sshd,            tags: sshd                  }
    #- { role: commons, task: firewall,        tags: firewall              }
    #- { role: commons, task: fail2ban,        tags: fail2ban_conf         }
    ##- { role: commons, task: cert,            tags: cert                  }
    #- { role: commons, task: rsyslog,         tags: rsyslog_conf          }
    - { role: nickhammond.logrotate,          tags: logrotate             }
    # - { role: commons, task: is_monitored,    tags: monitored             }
    # - { role: commons, task: backupamsmongo,  tags: rsyslog_conf          }



#- hosts: kafka_cluster
#  become: yes
#  roles:
#    #- { role: private_hosts }
#    #- { role: zookeeper, tags: zookeeper_install }
#    - { role: kafka,     tags: kafka_install }
#    #- { role: ams, task: deploy, tags: ams_install }
#    #- { role: ams, task: deploy_metrics, tags: ams_install }
#    #- { role: ams, task: init_db }


- hosts: kafka_cluster
  become: yes
  remote_user: root
  roles:
    - { role: commons,  task: firewall,  tags: firewall }

- hosts: zookeeper_nodes
  become: yes
  roles:
    - { role: zookeeper, tags: zookeeper_install }

- hosts: kafka_nodes
  become: yes
  roles:
    - { role: kafka,     tags: kafka_install }




