---
# handlers file for Apache Kafka

- name: Restart Kafka
  systemd:
    daemon_reload: true
    name: kafka
    state: restarted
    enabled: true


# In version 2.8.0 of Apache Kafka they started trying to have Apache Kafka **without** Apache Zookeeper:
# Early access of replace ZooKeeper with a self-managed quorum
# https://kafka.apache.org/downloads#2.8.0

- name: Wait Kafka to startup
  wait_for:
    timeout: "{{ kafka_health_check_delay }}"

